[tool.poetry]
name = "reflex-chakra"
version = "0.6.1"
description = "reflex using chakra components"
authors = ["Elijah Ahianyo <elijah@reflex.dev>"]
readme = "README.md"
packages = [{ include = "reflex_chakra" }]

[tool.poetry.dependencies]
python = "^3.9"
reflex = {git = "https://github.com/benedikt-bartscher/reflex.git", rev = "run-mode-helpers"}

[tool.poetry.group.dev.dependencies]
pytest = ">=7.1.2,<8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
